version: 2.1
orbs:
  architect: giantswarm/architect@0.4.5

jobs:
  build:
    machine: true
    steps:
    - checkout

    - run:
        name: Get architect binary
        command: |
          wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
          chmod +x ./architect
          ./architect version

    - run: ./architect build
    - persist_to_workspace:
        root: .
        paths:
        - ./aws-attach-ebs-by-tag
        - ./architect

  deploy:
    machine: true
    steps:
    - checkout

    - attach_workspace:
        at: .

    - run: ./architect deploy

workflows:
  build_and_push:
    jobs:
<<<<<<< HEAD
      - build:
=======
      - build
>>>>>>> 795e359c17babbe6d151a96198bf602a8dbbfbe2
      - architect/push-to-docker-legacy:
          name: push-aws-attach-ebs-by-tag-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/aws-attach-ebs-by-tag"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build

      - deploy:
          filters:
            branches:
              only: master
          requires:
          - build
